// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportImage'](arg1, arg2, arg3);
}

export function GetImageDimensions(arg1) {
  return window['go']['main']['App']['GetImageDimensions'](arg1);
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function LoadImages(arg1) {
  return window['go']['main']['App']['LoadImages'](arg1);
}

export function ReorderImages(arg1, arg2) {
  return window['go']['main']['App']['ReorderImages'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SortImagesByName(arg1) {
  return window['go']['main']['App']['SortImagesByName'](arg1);
}

export function SortImagesByTime(arg1) {
  return window['go']['main']['App']['SortImagesByTime'](arg1);
}

export function StitchGridImages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StitchGridImages'](arg1, arg2, arg3, arg4);
}

export function StitchImages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StitchImages'](arg1, arg2, arg3, arg4);
}

export function StitchPosterImage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StitchPosterImage'](arg1, arg2, arg3, arg4);
}
