// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportImage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetImageDimensions(arg1:Array<number>):Promise<number>;

export function GetTemplates():Promise<Array<main.PosterTemplate>>;

export function LoadImages(arg1:Array<string>):Promise<Array<main.ImageInfo>>;

export function ReorderImages(arg1:Array<main.ImageInfo>,arg2:Array<number>):Promise<Array<main.ImageInfo>>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveImage(arg1:Array<number>,arg2:string):Promise<void>;

export function SortImagesByName(arg1:Array<main.ImageInfo>):Promise<Array<main.ImageInfo>>;

export function SortImagesByTime(arg1:Array<main.ImageInfo>):Promise<Array<main.ImageInfo>>;

export function StitchGridImages(arg1:Array<main.ImageInfo>,arg2:main.LayoutConfig,arg3:number,arg4:number):Promise<Array<number>>;

export function StitchImages(arg1:Array<main.ImageInfo>,arg2:main.LayoutConfig,arg3:number,arg4:number):Promise<Array<number>>;

export function StitchPosterImage(arg1:Array<main.ImageInfo>,arg2:main.PosterTemplate,arg3:number,arg4:number):Promise<Array<number>>;
